server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
    url: jdbc:mysql://127.0.0.1:3306/mysql?useUnicode=true&characterEncoding=utf8&transformedBitIsBoolean=true&autoReconnect=true&serverTimezone=Asia/Shanghai&useCursorFetch=true&rewriteBatchedStatements=true
